### ISSUE TITLE
Feedback on "Splits" section

### ISSUE THREAD

**Issue by pfalcon** [portfolio-performance/portfolio-help#109]
@hug-sch, Thanks for taking lead in developing PP docs, it's much appreciated (btw, did you to announce availability of the docs on sites like Reddit, etc.?)

I'd like to share some feedback on the https://help.portfolio-performance.info/en/how-to/recording-stock-split/ page:

1. The page starts with:

> A stock split increases the number of shares in a company.

There're set of formal definitions when the above statement is 100% correct. But there're also other set of formal definitions when the above is not correct, and it would be nice to start with something which encompasses *both* normal and reverse splits right away. So, can we have it like "A stock split changes the number of shares in a company." ?

2. The narrative somehow presents that user has 2 choices: a) either use PP's split function, and have both historical prices and existing transactions be adjusted; b) don't use PP's split function, and don't have historical prices and existing transactions be adjusted.

I'd actually (in the intro section) stated that recording a split boils down to 2 separate tasks (and decisions): a) adjust or not historical prices; b) adjust existing transactions, or add new ones to keep share count and prices right.

PP's Split function always adjust historical prices (and arguably, that's the right way, why all financial sites to that). However, it offers a choice to user to either adjust existing transactions or not. It's a checkbox "Convert transactions" on second dialog page (after pressing "Next>" button).

I know that some brokers use equivalent of your described "sell-buy-back" method, for such users just need to adjust historical prices and be done with it.

3. For "sell-buy-back", you write "Sell all the shares at the closing price of the day preceding the split."

That's definitely one of the approach. But as you show yourself, it leads to extra complications in assessing performance. "(IRR = 1.03%). Prices have been increased since then. The previous period (the closed trade) however was negative (IRR= -8.40%). This puts the overall negative security performance of -6.11 in perspective." - are you sure IRR number are additive like that? It's easy to prove they aren't: suppose something went from 100 to 200 in 1 year. That's 100% IRR. Then 200 went to 100 in 1 year. That's -50% IRR. It may seem that IRR over 2 years is 50%, but actually it's 0%. There're IRR ranges where addition leads to small error, but do you know that range for a particular error limit, and do you want to teach folks all tricks at once? I however hope you don't want to teach folks incorrect things, like that they can add IRRs. **EDIT**: Withdrawn suggestion which follows. It works for "Return" aka "%P/L", but actually doesn't work for (annualized) IRR, which is calculated based on time shares held. ~~One tricks worth teaching is however that 0% IRR is certainly additive to any other IRR. And that's the idea - when you have a transaction forced upon you (like split) which may complicate performance calculation, make it 0% IRR. That means that "sell" transaction should sell for whatever was buy amount, including overheads. E.g., if original purchase amount was 100 with 1 commission, then selling for 101 will lead to %0 P/L and thus 0% IRR. That amount should be also "buy" amount for after-split transaction.  Per-share price is irrelevant, PP will calculate it from the stated amount.~~

I'd recommend to at least present such a scheme as an alternative, but due to complications with "use pre-split close price" (namely, IRR combination issue), you may want to consider making  it "the" method to recommend to users.

(This also reminds me that I wanted to ask @buchen for formal specification of how P/L figures for "transfer" transactions are calculated in PP. And if it's not the above, then I'd argue the above should be one of the options to deal with them (i.e. leave 0% P/L in the original account and "transfer" all of it to new), assuming there're also other viable choices to do it.)

**Comment by hug-sch** [comment]
@pfalcon Thanks very much for your valuable feedback. Much appreciated.

(1) It is indeed better to take the general stance and immediately discuss both regular and reverse stock split. I will update the text.

(2) If I understand you correctly, there are 4 alternatives (BTW, it is possible *not* to adjust historical prices in PP's split function; second check box in last step; see [reference section](https://help.portfolio-performance.info/en/reference/view/securities/context-menu/#stock-split) in the docs).

  (a) adjust historical prices and change the (previous) transactions: both checkboxes are checked in PP 's split function. This is probably the default choice for most users.
  (b) adjust historical prices but do NOT change transactions. 
  (c) do NOT adjust historical prices but change transactions. Can you see any benefit to these choices?
  (d) do NOT adjust historical prices and do NOT change transactions = do not use the split function.
So, in fact, this leaves us with two choices: use the split function or use the sell-buy-back option. Or, am I missing here something?

(3)I like your solution for the sell-buy-back method. Do you see any disadvantages for using the same purchase price instead of the closing price?

**Comment by pfalcon** [comment]
@hug-sch: 

Thanks for replies and finding some suggestions helpful. Sorry for the delay with response - I wish I  had more time to work on PP, but actually it happens much more intermittently where one (vacation) week I have time to look at many different things in PP, and then weeks w/o a chance to follow-up. Also, it's easy to reply "no-no, my way is the best without any drawbacks", but of course I myself just learning things and the whole area is complicated and multi-faceted.

> (3)I like your solution for the sell-buy-back method. Do you see any disadvantages for using the same purchase price instead of the closing price?
> However, I don't understand one item from your previous suggestion (using the original purchase price instead of the price immediately before the split). According to my calculations; there would be no difference in the IRR or TTWROR. Am I missing something?

Ok, so we here actually tried to apply this idea to a fresh SCHD split, and look at it critically to see if there're any drawbacks. And yes, having a fresh case really helps to spot one. So, my original idea with using original purchase price for both open and close price in 1st of 2 transaction was to ensure that "Return" (aka %P/L) of it was 0%, which would "push" any "Return" into 2nd transaction. Which is kinda helpful, I thought. But as soon as we add time-based criteria like IRR or TTWROR, they're thrown off by such handling. For example, 1st transaction would have IRR of 0%, as expected, but then IRR for 2nd xact would be calculates as if entire price appreciation happened since the split. Which in case of SCHD, where split happened just a couple of days ago, it would show thru the roof IRR of many thousands of percent. Of course, over time it subsided to more realistic figures, but it's clear that it's quite obvious and confusing artifact anyway.

So yes, using the closing price pre-split is a better approach, and I withdraw the suggestion of using initial purchase cost. If there were other suggestions in which you find some rational seeds, I'm glad, and thanks for the discussion.

**Comment by hug-sch** [comment]
@pfalcon 
OK. It's clear now. Thanks.
