### ISSUE TITLE
Wrong picture

### ISSUE THREAD

**Issue by Nirus2000** [portfolio-performance/portfolio-help#110]
Hello
On the page https://help.portfolio-performance.info/en/how-to/requesting-new-importer/ the wrong image is used in the description under “Convert these PDFs to text documents, one by one.”. The CSV is used here (templates), but not the extraction of a PDF debug.

![grafik](https://github.com/user-attachments/assets/04de7810-c149-4672-9d38-e9b041021af5)

Regards
Alex

**Comment by Kami-prog** [comment]
maybe this will help
https://bit.ly/3XQLHlH

you may need to install the c compiler

**Comment by hug-sch** [comment]
@Nirus2000 Hi, I re-used the image from [Reference > File > Import](https://help.portfolio-performance.info/en/reference/file/import/) but, it is indeed better to use here a more specific image. I've updated the docs.
