### ISSUE TITLE
Align Program and Documentation Terminology

### ISSUE THREAD

**Issue by flywire** [portfolio-performance/portfolio-help#27]
While technically correct, https://help.portfolio-performance.info/en/reference/ describes _panels_ while PP used the terms _sidebar_ and _information pane_ for the same objects. The documentation should use the same terms as the program.

_Top panel_ would probably better be described as _Main pane_.

**Comment by flywire** [comment]
The term _form_ might be more appropriate than _panel_ in some places.

**Comment by hug-sch** [comment]
Thanks for the reviewing and comments! I've changed the accompanying figure as well.
