### ISSUE TITLE
Unlisted Securities

### ISSUE THREAD

**Issue by flywire** [portfolio-performance/portfolio-help#81]
Unlisted security example descriptions would be useful.

Relevant forum questions:

1. https://forum.portfolio-performance.info/t/handling-of-unlisted-securities-scrip-dividends/3960
1. https://forum.portfolio-performance.info/t/tracking-the-aum-and-performance-of-individual-accounts-and-sub-accounts/19329

**Comment by Sn1kk3r5** [comment]
Hi @flywire,

should be covered now:

New Security: https://help.portfolio-performance.info/en/reference/file/new/#security
Taxonomy for sub Accounts: https://help.portfolio-performance.info/en/reference/file/new/#taxonomies

Cheers

**Comment by Sn1kk3r5** [comment]
PS. 

If you have further input or missing stuff, feel free to post each individually, so we can keep track on them a create PR's based on the finding.

Cheers
