### ISSUE TITLE
Check spelling and grammar / standardization of videos, images and screenshots

### ISSUE THREAD

**Issue by Nirus2000** [portfolio-performance/portfolio-help#82]
Referenz: #77

Bitte vor pull request.... [Rechtschreibprüfung](https://rechtschreibpruefung24.de/) durchlaufen lassen sowie
[Grammatikprüfung](https://languagetool.org/de/) absolvieren.

Es sind soooooooo viele Fehler und falsche Formulierungen drin.

---

@hug-sch 
Please write the Contributing Rules so that a uniform standard is developed.

please before pull request.... run through [spell check](https://rechtschreibpruefung24.de/) and
[grammar check](https://languagetool.org/de/).

There are soooooooo many mistakes and wrong formulations in it.

**Video setting: (First thoughts)**

- At least Full HD resolution - 1080p (1920x1080)
   - I don't know... maybe 1024x768? I dont know...
- Subtitles <->Text possibly in German/English?
   - No sound
- Defined image section of the video content
   - If possible exclusively in the PP software
   - Use in example file → Kommer.xml which is in PP
   - No private PP file with data
   - No private desktop background (solid color)
   - Portfolio performance in "light" mode (no dark)
   - z. e.g. in Windows or Mac → Standard design → "Light" mode (no dark)
   - etc.

**Picture/Screenshot setting: (First thoughts)**

- Use in example file → Kommer.xml which is in PP
- If possible exclusively in the PP software
- At least Full HD resolution - 1080p (1920x1080)
- No private desktop background (solid color)
- No private PP file with data
- Portfolio performance in "light" mode (no dark)
- e.g. in Windows or Mac → Standard design → "Light" mode (no dark)
- etc.

_Originally posted by @Nirus2000 in https://github.com/portfolio-performance/portfolio-help/issues/77#issuecomment-2099938314_

**Comment by hug-sch** [comment]
Updated contributing.md
