### ISSUE TITLE
Screenshot in englisch

### ISSUE THREAD

**Issue by Nirus2000** [portfolio-performance/portfolio-help#94]
Hallo @Sn1kk3r5 
super Arbeit bisher.... Rechtschreibung... Grammatik.... sehr geil! Saubere Arbeit !! 👍🏻 

Eine möchte nochmal den Hinweis geben, dass die Bilder (Screenshots) einheitlich sein sollten.
In Portfolio Performance bitte das "Helle Layout" verwenden, da der "Dark Mode" in den unterschiedlichen Betriebssystemen sich sehr unterscheidet. Die meisten Übereinstimmungen sind eben im "Hellen Modus", was die Standardeinstellung ist. 
Auch bitte darauf achten, dass Ihr deutsche und englische Screenshots nicht vertauscht.

Gruß
Alex #

_Originally posted by @Nirus2000 in https://github.com/portfolio-performance/portfolio-help/pull/92#discussion_r1609264836_

**Comment by Sn1kk3r5** [comment]
https://github.com/portfolio-performance/portfolio-help/pull/92#discussion_r1609454133
